- src/filesystem/root/etc/haproxy/haproxy.cfg
I have no idea  how that crept into a *copy and paste* but my guess is that that's the reason for #60 (at least it behaves exactly the same when I change my haproxy config to that). Sorry for that, again, I have no idea how that happened, I copy pasted the config.
> Fixed typo causing #60 and caused by #50

- src/chroot_script
At least I got compile errors without that. That plus
https://github.com/jacksonliam/mjpg-streamer/pull/3 (after
merge!) should fix the mjpg_streamer issues with kernel 3.18
> New library needed for compiling mjpg_streamer

- src/build
- src/chroot_script
- src/common.sh
- src/config
- src/octopi
- src/util.sh
- src/variants/example/chroot_script
- src/variants/example/config
- src/variants/example/config.nightly
added support for variants that modify the octopi build. introduced a folder 'variants' in which each variant occupies a subfolder. these subfolders can have config files, chroot_scripts and filesystem overlays just like the original octopi build script, which get applied after the base octopi image is built. flavors just are different config files at the moment. 
see src/variants/example for and example.
> Support for OctoPi variants and flavors (like mr beam's fork)

- src/chroot_script
Due to the site-package being active in the OctoPrint
virtualenv, sometimes the site wide installed version
of pyserial got used, leading to errors when trying
to connect to 250k baud firmwares.
Just removing the preinstalled variant (which contrary
to some reports seems to NOT include the patch for
250k support) solves that.
> Fix for guysofl/OctoPi#84: Uninstall python-serial

- src/filesystem/root/etc/default/octoprint
This will prevent connections to http://<ip>:5000 from working and
hence hopefully reduce the amount of support requests by users who
connect with port 5000 for whatever reason and then don't understand
why their webcams won't work.
Should probably only be merged once the fix for #95 has been merged,
since this effectively makes OctoPi only serve OctoPrint if haproxy
is actually running.
> Bind OctoPrint only to 127.0.0.1

- src/filesystem/home/scripts/genCert
While this doesn't solve the problem of these files being generated
at 0 bytes size in the first place, it at least should make
OctoPi reattempt to generate the certificate and thus fix the
issue described in #95 (possibly after a couple of reboots).
> Fix for #95: Check for zero sized ssl files

- src/filesystem/home/.octoprint/config.yaml
The plugin now is bundled with the current devel of OctoPrint,
this makes it work on OctoPi (although since this configuration
limits it to updating to releases only nothing can be seen
yet).
> Added configuration for Software Update plugin

- src/common.sh
- src/octopi
Helps a lot in checking out the image after building since 
source common.sh
mount_image $image_path $mount_path
is way faster typed down than 2 x `mount -o loop,offset=....`
if you just want to quickly mount it to look if some file looks
correct.
> Moved mount/umount commands to functions

- src/chroot_script
- src/filesystem/home/root/bin/git
This will be found first when executing sudo git and checks whether
it is running with super user privileges and if so refuses to do
that and instead just prints a friendly message to please run git
without sudo.
Reason: Apparently users tend to do a "sudo git pull" when updating
OctoPrint, effectively screwing up their permissions in the process
and then running into problems later on. This should hopefully act
as an educational measure to stop this from happening.
> Added wrapper script for git for sudo

- src/build
Out of the box logs whole build output into `build.log`. Logfile can be specified through environment variable `LOG`, e.g.
By setting that variable to the value `no`, no logfile will be created (old behaviour):
> Create a log file of the whole build

- src/chroot_script
- src/filesystem/home/pi/.octoprint/config.yaml
Install pybonjour & set external port in config.yaml to publish `_octoprint._tcp` and `_http._tcp` mdns services on. Pybonjour also needs `avahi-daemon` and `libavahi-compat-libdnssd1`, so moved the former up from further down in the script and added the latter.
When this patch is applied, OctoPrint should announce itself on the local network as both HTTP and OctoPrint service (and also allow plugins to utilize the mdns helper functionality included in OctoPrint's bundled discovery plugin to discover mdns services on the local network such as Growl servers).
> Enabled proper discovery of OctoPrint

- src/filesystem/boot/octopi.txt
- src/filesystem/home/pi/scripts/webcamDaemon
For whatever reason using the -f parameter with that specific camera
model causes it to just not output any image. mjpgstreamer will start
up just fine and not log an error or anything, the camera will appear
to start up too, but when connecting to the webcam stream nothing will
be displayed at all. Just removing the -f parameter in this case fixes
it completely.
This patch adds a new check to the webcamDaemon when starting up a
USB webcam which checks the webcams USB vid and pid against a list
of webcams known not to work with -f (right now that's just the C170,
but more can be added easily by the user through the new
additional_brokenfps_usb_devices option in /boot/octopi.txt) and if
a match is found strips the -f parameter from the camera options.
This is the only way I found I could …
> Fixes webcamDaemon for Logitech C170

- src/chroot_script
- src/filesystem/boot/octopi-network.txt
`/etc/network/interfaces` file is modified such that it includes
a new file `/boot/octopi-network.txt` which contains sample config
snippets for getting wifi connectivity configured for WPA/WPA2-PSK,
WEP and unencrypted and also for a static IP on a virtual second
ethernet port.
This way after flashing the image to the SD the user can just
edit that file (which is on the root of the FAT partition which
desktop OSs should usually offer to access just when plugging in
the card), uncomment the matching configuration snippet, fill
in the credentials (SSID and password, or just the SSID in case
of an unencrypted WiFi), save, put the card in the Pi's SD card
slot and their USB WiFi dongle in a USB port, boot and have their
Pi directly on their network. No more cable needed, no problem
to …
> Allows network configuration without booting

- src/filesystem/home/pi/.octoprint/config.yaml
When issuing one of the restart/reboot/shutdown commands
from the system menu, the request could not be acknowledged
anymore because the server was already gone, leading to the
client displaying an error for the command execution just
before the offline overlay.
To stop things like this from happening, 1.2.0 introduced
two new parameters for system actions, asnyc and ignore.
async makes the request return without waiting for the
result of the command's execution. ignore makes the client
ignore any errors in the command's execution.
The combination of both yields successful restarts/reboots/
shutdowns without scary messages.
> Suppress error when using restart command

- README.rst
Added some more steps to the usage instructions for the new
network setup mechanism and explained CuraEngine setup needs
slicing profile to be added by the user.
Also fixed typos where I stumbled over them.
> README update: usage instructions & typos

- src/chroot_script
- src/filesystem/boot/octopi-network.txt
- src/filesystem/home/root/bin/map_iface
- src/filesystem/root/etc/logrotate.d/map_iface.log
Will decide between OctoPi and Raspbian type of network
configuration depending on whether the user set up a network
configuration in /boot/octopi-network.txt or not.
A mapping script will try to see if it can find an uncommented
line
iface $IFACE-octopi
in /boot/octopi-network.txt. If so, the user obviously used this
method to setup their network credentials (the lines are usually
all commented out) and $IFACE will be mapped to use the
$IFACE-octopi definition from that file. If no such line is
found, $IFACE will be mapped to $IFACE-raspbian, which is the
default wlan0/wlan1 configuration shipped with vanilla Raspbian.
See also #122
> Added mapper for network configuration

- src/chroot_script
- src/config
- src/nightly_build_scripts/build_local_mirrors
- src/nightly_build_scripts/octopi_nightly_build
`gpio` commands should work directly for toggling pins etc.
Should fix #51
@guysoft Please verify that the adjusted nightly build scripts are
ok this way, I use the source repositories directly instead of working
with mirrors. Not going to merge this until you confirm it is working for your setup.
> Added wiringPi to image

- src/chroot_script
This way we can use up to date versions of urllib3 etc that
do not have bugs...
This should solve #155
> Make oprint a non-system-side-package virtualenv

- src/common.sh
Greps for file system types of boot and root partition instead
of relying on line numbers in sfdisks output
> Better image offset calculation for mounting

- src/chroot_script
- src/common.sh
- src/config
- src/filesystem/boot/octopi.txt
- src/filesystem/root/etc/init.d/gencert
- src/filesystem/root/etc/init.d/prepare_resize
- src/octopi
If `OCTOPI_IMAGE_ENLARGEROOT` is set to a size (in MB), the
root partition of the raspbian image will be enlarged by that
size before starting the actual build. This helps in situations
where the image doesn't ship with enough space to perform the build.
If `OCTOPI_IMAGE_RESIZEROOT` is set to a size (in MB), after the
build the image will be resized to its minimal size plus the provided
size. 200 MB appears to be a good value here.
On first boot the image now resizes itself to take up the full SD size unless
`perform_resize` is set to a value != `yes` in `/boot/octopi.txt`.
> Better size management for SD card image

- src/common.sh
Instead of matching partition types, match partition number.
Apparently matching partition types can be somewhat flaky considering your recent build results (didn't have any issue on my tests though... odd that, probably slightly different sfdisk output)
> Even better image mounting

- src/nightly_build_scripts/cleanup_storage.js
Should be executed _before_ generating the index. Will remove all nightlies for RPi and BPi that are older than 14 days.
Has two modes of operation: When called with `print` as first parameter, will only output the files that would be deleted. When called with `delete` as first parameter, will actually delete the files.
So, for testing:
`node cleanup_storage.js print`
and in the build
`node cleanup_storage.js delete`
> Added a clean up script

- src/config
- src/octopi
We might not want a custom variant for something like having to swap
resolv.conf or similar just to make the image buildable on certain
environments, so this adds a build environment specific additional means
to inject scripts into the build process.
Example: build server that requires a special set of nameservers in
/etc/resolv.conf during build.
> Allow specification of an additional pre/postscript

- src/common.sh
We might have "broken" mounts in the mix that point at a deleted image (in case of some odd
build errors). So our "sudo mount" output can look like this:
/path/to/our/image.img (deleted) on /path/to/our/mount type ext4 (rw)
/path/to/our/image.img on /path/to/our/mount type ext4 (rw)
/path/to/our/image.img on /path/to/our/mount/boot type vfat (rw)
so we split on "on" first, then do a whitespace split to get the actual mounted directory.
> More resilient unmount

- src/filesystem/root/etc/haproxy/errors/503-no-octoprint.http
- src/filesystem/root/etc/haproxy/haproxy.cfg
Should help users to understand why they are not seeing their
OctoPrint interface but instead an error from haproxy if the server
is not (yet) running.
> Custom error page in haproxy for 503 error

- src/filesystem/root/etc/haproxy/errors/503-no-octoprint.http
- src/filesystem/root/etc/haproxy/errors/503-no-webcam.http
- src/filesystem/root/etc/haproxy/haproxy.cfg
Currently the "OctoPrint server not running" page will also be shown when navigating to the `/webcam` path (e.g. to check the webcam server manually outside of OctoPrint), and imply the OctoPrint server being down when in fact it's the webcam server that's down. This solves that issue, improves on the troubleshooting steps for the "OctoPrint server down" situation and adds a whole new error page including troubleshooting steps for the "webcam server down" situation.
In a nutshell:
* Better wording on existing "OctoPrint server not running" error page
* New error page for "Webcam server not running"
* configuration change in haproxy to show octoprint one only for
503 in OctoPrint backend and webcam one only for 503 in webcam
backend. 
* Also removed some unused CSS from the error pages …
> Better "service not running" error pages

- src/filesystem/boot/octopi-network.txt
It might lend to confusion when the static IP address is set to `192.168.250.10` and then suggested that the system can be reached from `192.168.250.1`, this is obviously a typo.
> Corrected the IP address in the network settings instructions

- src/vagrant/Vagrantfile
which has the guest additions installed.
This is nesacerry because the old box was not able to provision right due to problems with mounting. See issue #264.
> changed vagrant box to "wzurowski/vivid64"... 

- src/filesystem/home/pi/.octoprint/config.yaml
Some things were switched around in OctoPrint, doesn't make sense to ship with the old config.yaml layout (even though it would be automigrated).
> Adjusted config.yaml to match layout of OctoPrint 1.3.x

- src/chroot_script
We no longer need to manually setup a solid SSL environment since that's already done for use with Python 2.7.9. The whole issue that we ran into with setting this up under Pip 9+ therefore can be circumvented without having to pin the pip version.
Refer to #276
Note: as far as I could tell, Armbian should also ship with Python 2.7.9 (which is the default version under Jessie), so this change shouldn't cause any issues in the build variant either I hope.
> Remove pip version pin

- src/filesystem/root/etc/init.d/octoprint
Running in foreground mode requires "serve" keyword since 1.3.0. Still works without, but logs a warning to console.
Also fixed a couple of misspellings of OctoPrint in the init file while at it (capital P in the middle!) ;)
> Adjusted init script to new OctoPrint CLI

- src/chroot_script
- src/filesystem/home/pi/scripts/welcome
Two commits doing the following (provided as a single PR because otherwise you'd have to resolve a conflict for merging - the third commit - and they are pretty related):
A lot of people appear to get confused when they boot up OctoPi with a screen attached and are then greeted by a command line login instead of OctoPrint.
Therefore added instructions to please use a browser to connect to a list of potential addresses to access OctoPrint - that might help.
Upon logging in via command line, the user will now get the following information:
* IPs/URLs to access OctoPrint
* Hint how to install desktop environment if not already
installed
* Versions of OctoPrint and OctoPi
Looks like this:
```
The programs included with the Debian GNU/Linux system are free software;
the exact distribution …
```
> Make CLI a bit more helpful for newbies

- src/chroot_script
While I couldn't reproduce this issue on a current build, apparently
it doesn't necessarily have to happen always and the corresponding
ticket on the rpi bug tracker (raspberrypi/linux#1519) is still
open as well.
Hence this change. As documented at
https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=141454
and other locations, ntp updates on RPi3 (sometimes?) fail if the
built-in WiFi interface is used. This appears to be the same issue
or at least related to SSH not properly functioning as described
in #294 and also documented in raspberrypi/linux#1519.
A wrong system date of the underlying OS will cause issues with
SSL handshakes, which in turn will produce fatal errors when
attempting to install plugins (see foosel/OctoPrint#1827) or
probably also when updating either OctoPrint or …
> Prevent NTP updates from failing on RPi3 wifi

- src/chroot_script
- src/filesystem/home/root/bin/check_wpa_link
- src/filesystem/root/etc/systemd/system/check_wpa_link.service
Included script will make sure that if wpa_supplicant.conf is no
longer a symlink but it and /boot/octopi-wpa-supplicant.txt exist,
the selected wifi country will be extracted and written to
/boot/octopi-wpa-supplicant.txt and then the symlink will be
recreated. If wpa_supplicant.conf is completely gone, only the
symlink will be recreated. Nothing will be done if
/boot/octopi-wpa-supplicant.txt does not exist.
The service file ensures that this check is done on every boot,
after the local file system becomes available but before the
networking gets initialized.
This should solve #336
Note that this requires systemd (Debian Jessie) - since current
Raspbian starts SysV init scripts only after networking has
started to initialized, it was impossible for me to create a
SysV init script that …
> Service file to fix symlink for wpa_supplicant.conf

- src/chroot_script
- src/filesystem/boot/octopi.txt
- src/filesystem/home/root/bin/webcamd
Instead of ./www we now use ./www-octopi by default which only
contains an index.html (generated during image build) that displays
only the snapshot and stream for debugging purposes.
The command action on mjpg-streamer (which control.html of the stock
webroot utilizes) has also been disabled via "-n".
Two new variables have been introduced in /boot/octopi.txt to
allow configuring the webroot to use and the additional options
for output_http.so (by default only "-n"), in case power users
need to change back or otherwise customize stock behaviour.
Closes #358
> Custom webroot & disabled controls for webcam server

- src/build_dist
The script is flagged executable, but due to the missing shebang, only an error message is produced:
```
OctoPi/src (devel)> ./build_dist 
Failed to execute process './build_dist'. Reason:
exec: Exec format error
The file './build_dist' is marked as an executable but could not be run by the operating system.
```
> Add missing shebang

- src/config
Raspbian ships it by default this way and that's a really bad idea with regards to security. Sure, if an 
attacker already logged in through SSH because the user didn't change their password as suggested, 
an additional password request for a malicious sudo won't help either. But since we also have plugin system in OctoPrint, a system command editor and various other means for configuring command lines, we don't want to make abusing those too easy.
Note: Also adjusted the existing sudoers files for allowing service and shutdown (through OctoPrint) - turns out it's no longer /sbin/service but /usr/sbin/service now and to be safe we are now using which here
@guysoft This is something that has made me very very uncomfortable for a while now and I'd really feel better if sudo wasn't generally …
> Do not allow passwordless sudo for user pi

- src/modules/octopi/filesystem/home/root/bin/git
Some users run into issues with the git wrapper preventing usage as root when trying to install third party software on OctoPi that for some reason requires to run git as root. See comments to #114 and #373.
This adds a small message to the output generated by the wrapper script to explain to people how to remove the wrapper in order to allow for that kind of usage of git.
> Add instructions on how to remove git wrapper

- src/modules/octopi/filesystem/home/root/bin/webcamd
The GEMBIRD webcam is brokenfps.  Adding the webcam's usb id to the list allows the webcam to work.
Here's the device's USB:
Bus 001 Device 005: ID 1908:2310 GEMBIRD 
This is the camera:
https://ae01.alicdn.com/kf/HTB1OlilPpXXXXbWaXXXq6xXFXXXW/Newest-Webcam-USB-12-Megapixel-High-Definition-Camera-Web-Cam-360-Degree-MIC-Clip-on-For.jpg
Here's where I bought it: https://www.aliexpress.com/store/product/FW1S-USB-2-0-Webcam-12-0-Mega-Pixel-HD-Camera-Webcam-360-Degree-MIC-Clip/1283494_32659656232.html
> Add GEMBIRD webcam to list of brokenfps_usb_devices

- src/modules/octopi/config
- src/modules/octopi/filesystem/home/pi/.octoprint/config.yaml
- src/modules/octopi/filesystem/home/pi/OctoPrint/README.txt
- src/modules/octopi/filesystem/home/pi/scripts/add-octoprint-checkout
- src/modules/octopi/start_chroot_script
OctoPrint 1.3.6+ no longer relies on git for updating itself,
so there's really no use to ship with a full blown git checkout
any more.
In case people miss that however, there's a README.txt in place
that tells people how to get it back if they do need it.
> Install OctoPrint from network via pip

- src/modules/octopi/filesystem/boot/octopi-network.txt
If a user follows some outdated docs after the release of 0.15,
we still want them to find something that helps them get things
running.
Complements https://github.com/guysoft/CustomPiOS/pull/19
> Add "redirect" for octopi-network.txt

- src/config
We so far followed MAJOR.MINOR.PATCH as version scheme. I suggest we stay there to not confuse people ("why does 0.15 follow 0.14.0?").
> Back to MAJOR.MINOR.PATCH version scheme

- src/modules/octopi/filesystem/home/root/bin/webcamd
The code was checking that /dev/video0 exists, however I may sometime have the webcam as /dev/video1 and the check failed. This will check with /dev/video? wildcard.
My editor also cleaned some whitespace.
> Checking for multiple usb webcams instead of /dev/video0

- src/modules/octopi/filesystem/home/root/bin/webcamd
So sorry, I forgot bash is strict about white space when setting a variable. Fixed, and tested on real OctoPi.
> Fixed white space to fix setting the video_device_count variable

- src/modules/octopi/filesystem/home/root/bin/webcamd
Genius WideCam F100 is a popular webcam for 3D-printers because of it's very wide FOV @ 120 deg.
It only supports one specific frame rate per resolution so disabling the frame rate option is the best option.
This will also fix #365 so that can be closed.
> Add Genius WideCam F100 to brokenfps

- src/modules/octopi/filesystem/home/root/bin/webcamd
This patch tries to allow detection of usb webcams. It also corrects a small regular expression problem.
* When polling for webcams, we check for cameras by listing all video devices, and if at least one is found, we give the path of the first device to startUsb function. 
* StartUsb will use the device given as the parameter. It also has an option override the first found device which is pssed as a parameter, if it's explicitly set in the /boot/octopi.txt.
* If the device is not given it the octopi.txt, we will add the device path as a parameter for mjpeg-streamer, into the options variable.
* The unescaped "+" sign that was used in the regular expression with sed, to get data for the extracted_device variable, is now also correctly escaped, and the expression works now on OctoPi.
* The …
> Support for other webcams than /dev/video0, fixed a regular expression

- src/modules/octopi/filesystem/boot/octopi.txt
- src/modules/octopi/filesystem/home/root/bin/webcamd
They were only added to the (by default commented out) config line
in octopi.txt but missing in webcamd. Also the defaults weren't
properly documented.
> Fix definition of some broken webcams

- src/modules/octopi/filesystem/root/etc/haproxy/errors/503-no-octoprint.http
- src/modules/octopi/filesystem/root/etc/haproxy/errors/503-no-webcam.http
They were still pointing to the now locked down mailing list and G+ community, and one FAQ item link also needed to be changed.
> Point the support links on the error pages to the forum

- src/modules/octopi/filesystem/home/root/bin/webcamd
Fills up the syslog with May 29 06:25:03 octopi kernel: [78101.764331] pwc: Iso frame 7 has error -71 (till the disk is full)
>  Don't try FPS with Philips (or NXP) PCVC740K ToUcam Pro [pwc]

- README.rst
docs do not specify anything about the venv, thus finding pip took a second to learn how to install plugins
clarify `pip` location
> docs(readme): clarify plugin installation

- src/modules/octopi/filesystem/home/pi/scripts/welcome
Brackets to be RFC2732 compliant
>To use a literal IPv6 address in a URL, the literal address should be enclosed in "[" and "]" characters.
It worked, (but the KDE console doesn't recognize it correctly as a link, without this fix firefox would complain and try it as a search)
> Put IPv6 addressess in brackets

- src/modules/octopi/filesystem/home/root/bin/git
Admittedly, this is a microoptimization, but we might as well run git with `exec` in the wrapper script. In the current incarnation bash stays open & takes a bit of extra memory but if we `exec` directly bash is completely replaced with the git process.
> Directly exec git instead of running child process

- src/modules/octopi/filesystem/home/pi/scripts/safemode
You would think that a set of simple instructions on how to set Safe Mode would be sufficient for most users. But again today, I find myself [teaching someone](https://community.octoprint.org/t/server-not-startet) basic Linux commands on the forum.
I've just created a script which in theory will add the Safe Mode toggle in what I hope to be a safe method of doing so. You might consider either putting this in the `pi` user's path or add a symlink to accomplish this so that we don't have to educate them on how to call the script by location.
> Added safemode script to toggle on Safe Mode once

- src/modules/octopi/filesystem/home/root/bin/webcamd
The `0x000137ab` frimware of `VL805` on Raspberry Pi 4 is known to cause problems with USB cameras - stream not working or working only in very low resolution (like QVGA `320x240`). See #621.
Choosing slightly higher resolution `640x480` causes streaming to fail: you can see a lot of `uvcvideo: USB isochronous frame lost (-18).` lines in the dmesg logs and `i: select() timeout` in the `mjpg_streamer`'s output.
You may need to enable uvcvideo's tracing to see those errors:
``` bash
echo 0xffff > /sys/module/uvcvideo/parameters/trace
```
For details see: https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=244421
> Add workaround for a bug in Raspberry Pi 4 VL805 0x000137ab firmware (streaming issues)

- README.rst
Without this, the link currently redirects incorrectly to `https://github.com/guysoft/OctoPi/blob/devel/octopi.local/webcam/?action=stream`
> Fixes stream link in readme

- src/modules/octopi/filesystem/root/etc/haproxy/haproxy.cfg
This spins out of a discussion at [OctoPrint#3529](https://github.com/OctoPrint/OctoPrint/issues/3529), where @flaviut did the math on how enabling http compression is really helpful, even on a little Pi. It'd be nice if we could get it enabled in Tornado, but this is easier and won't be invalidated by work on Tornado if that gets done.
haproxy attempts to compress every mime type, and it is a big win. You can go over to the other issue to see the comparisons. It doesn't seem to support setting a compression level, and [it is cautious](https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#compression), so it should be fine.
Tested locally.
> enable compression at haproxy layer

- src/modules/octopi/start_chroot_script
Standard Makefile is just wrapper on top of CMake, and -j option is not passed through.
I had to unwrap it.
MJPG Streamer tested working.
This change makes build on my i5-4278U 1 - 2 minutes faster.
> Unwrapped MJPG Streamer Makefile to apply -j option.

- .github/workflows/build.yml
> Limit artifact persistence to scheduled builds

- src/modules/octopi/filesystem/root/etc/haproxy/errors/503-no-webcam-hls.http
- src/modules/octopi/filesystem/root/etc/haproxy/haproxy.cfg
- src/modules/octopi/filesystem/root/etc/nginx/sites-available/default
- src/modules/octopi/filesystem/root/etc/systemd/system/ffmpeg_hls.service
* Proxied HLS through HAProxy to avoid CORS issues and streamline web serving.
* Made JPEG frames writing atomic.
* Tuned HLS stream.
> HLS proxying and tuning

- src/modules/octopi/filesystem/home/root/bin/webcamd
Noticed webcamd was accessible on all interfaces on port 8080. Fixed to only be accessible to 127.0.0.1 (localhost).
> added default listener to localhost for webcamd

- src/modules/octopi/config
- src/modules/octopi/start_chroot_script
OctoPrint no longer depends on it (it's no longer maintained and
also not compatible to Python 3) and instead now uses zeroconf.
As it's incompatible to Python 3 anyhow, installing it no longer
makes sense.
> Remove pybonjour dependency install

- src/modules/octopi/filesystem/root/etc/haproxy/haproxy.cfg
Testing the haproxy.cfg file using the version of haproxy installed by OctoPi generates a warning. 
HA-Proxy version on RasPi Buster is
HA-Proxy version 1.8.19-1+rpi1 2019/03/14
To test the config file by haproxy use the '-c' (check) flag as
`sudo haproxy -c -f /etc/haproxy/haproxy.cfg`
which generates the warning
```
[WARNING] 291/152612 (2843) : Setting tune.ssl.default-dh-param to 1024 by default,
if your workload permits it you should set it to at least 2048.
Please set a value >= 1024 to make this warning disappear.
```
HA-Proxy Documentation for tune.ssl.default-dh-param feature states 
``` Higher values increase CPU load and may not be supported by some clients (IE:Java 7).```
This only affects SSL traffic. Non-encrypted traffic is unaffected. 
Adding `tune.ssl.default-hd-param …
> Set HAProxy Diffie-Hellman key size to 2048

- src/modules/octopi/filesystem/boot/octopi.txt
[Myself, and others](https://community.octoprint.org/t/camera-raspi-options-seems-to-be-ignored/24939) have run into the problem of setting options for `camera_raspi_options` only to have them be ignored. It appears that this is due to some pi cam modules being detected as USB cams and not pi cams as described in #674 
Short of rewriting the camera detection code, this PR adds a note in the base `octopi.txt` to help people running into the issue.
The note reads:
```
NOTE: Newer raspi cam modules are reporting as usb devices causing these options to be ignored. Set `camera="raspi"` to avoid these 
```
> Add note about raspi cam options being ignored

- src/modules/octopi/filesystem/root/etc/systemd/system/webcamd.service
HI,
thanks for your work ! 
by default, when the service crash, it is restarted within 100 ms. This patch increase the time in order to eventually let the usb device to be ready.
This option is described here : https://www.freedesktop.org/software/systemd/man/systemd.service.html#RestartSec=
> Increase restart time to 1 second

- src/modules/octopi/filesystem/home/root/bin/git
Hi @guysoft,
I was just trying to install a application which obviously runs git as root on my octopi installation. I stumbled upon the git wrapper and temporary disabled it. But I couldn't figure out why this restriction was added until I looked it up in the issues: #373. I think it would be a good idea to not only tell the user what is happening and how they can resolve it, but also why this is happening. I've added a suggestion, but rather take it as a general idea :)
Best regards,
Ben
> Add explanation of git wrapper script

- src/modules/octopi/filesystem/boot/octopi.txt
- src/modules/octopi/filesystem/root/etc/systemd/system/networkcheck.service
- src/modules/octopi/filesystem/root/etc/systemd/system/networkcheck.timer
- src/modules/octopi/filesystem/root/usr/local/bin/networkcheck
- src/modules/octopi/start_chroot_script
Hi, i noticed from time to time (primary on very long prints with several hours) my pi has left the connection and was not comming back but print was still running until it's finish.
So i decided to create this as a prevention mechanism which monitors the connection and if needed it will restart the connection without restarting the whole system - so no print will be interrupted and system becomes reachable again :-)
Hope you like it!
> Add a network monitoring for wifi connections

- src/modules/octopi/start_chroot_script
Let's add avrdude for firmware flashing which is needed if done via octoprint and available plugins
> Add avrdude for firmware flashing

- src/modules/octopi/start_chroot_script
I believe this is why the builds began failing around March 12th.  It appears the version of Cmake changed from 3.13.4-1 to 3.16.3-3~bpo10+1.
I found this fix while examining why v1pi was failing to build.
Apparently current cmake (3.16) fails with the GLOB operation and it sounds like it's related to this issue
https://gitlab.kitware.com/cmake/cmake/-/issues/20568
According to that thread, this is a consequence of an update within 3.15, and (probably) fixed sometime before 3.19.
> Fix problem where cmake fails to detect compiler

- src/modules/octopi/filesystem/home/root/bin/webcamd
To fix #740 and restore the old behaviour of `webcamd` instead of having to rely on the startup to take care of regular polling, instead of existing after bringing up all devices in the background, we will now wait for all child processes to exit. Once that is the case, we'll reset the camera array, sleep 120s and restart the discovery process.
While debugging #740 I also noticed a bug when interacting with the RPi Camera v4l2 device files, which don't have a USB vid and pid and hence produced a syntax error when trying to convert those empty strings into hex for matching against the broken fps device list.
Finally, I found a bunch of typos or weird phrasing and also added some whitespace lines for easier readability.
Would be lovely if @usk-johnny-s could also take a look at the logic …
> Fix webcamd daemon loop & handling of non-usb v4l2 devices

- src/modules/octopi/config
- src/modules/octopi/start_chroot_script
Instead of fetching the latest release on GitHub with a GitHub API call and installing the zip from that, let's simply install right from PyPI. And if a specific version is desired it can still be configured ("OctoPrint==1.6.1").
> ♻️ Install OctoPrint from PyPI

- src/modules/octopi/filesystem/root/etc/systemd/system/ffmpeg_hls.service
When using the experimental HLS camera streamer, an image snapshot is being generated for each frame, encoded to JPG and atomically written to the filesystem.
This creates a huge CPU cycle and IO burden at the configured 30 fps -  when running on a Raspberry 3B, the current setup consumes over ~70% CPU.
With this PR, ffmpeg is configured to only generate a snapshot once a second, reducing the resulting CPU load to ~20% on a RP 3B.
> [Improvement] When using HLS camera streamer, generate frame snapshot only once a second

- src/modules/octopi/config
- src/modules/octopi/start_chroot_script
This removes the version pin on cmake and removes wiringpi, which is no longer maintained and now not even available in the repository anymore.
Note that this currently will in all likelihood not build because there's an unrelated issue with a Python dependency `regex` currently ongoing that the OctoPrint build is depending on (see mrabarnett/mrab-regex#443). I'm hopeful that that will be fixed soon though (the dependency was updated today and the release lacks some mandatory files). Marking this as draft for now until I can confirm.
I was temporarily able to work around the aforementioned issue by injecting
sudo -u "${BASE_USER}" /home/"${BASE_USER}"/oprint/bin/pip install regex==2021.11.2
into the chroot script, and can confirm that the build runs through then after the changes in this …
> Fix building against bullseye

- src/modules/octopi/start_chroot_script
mjpg-streamer doesn't work anymore with the new picam stack on bullseye based images - using the old stack for now.
> picam-bullseye-fix

- src/modules/octopi/start_chroot_script
The 64bit images are currently lacking vcgencmd, meaning that the
PiSupport plugin can't check for undervoltage and overheat
situations and will complain about this in the latest version
as well, see feedback in #770.
This should fix it by installing the package containing vcgencmd
and making sure the base user is added to the video group as
well.
**I was not able to test this in a build since I could not find
documentation on which base image exactly to use and how
to precisely run the 64bit build, but based on user feedback
it should hopefully work. Still, please test in a build before
merging.**
> Install vcgencmd and fix user permission on Ubuntu

- src/modules/octopi/filesystem/root/etc/haproxy/haproxy.2.x.cfg
I was fixing my OctoPi install after doing a dist-upgrade (buster to bullseye) and breaking haproxy in the process... I fixed that issue by replacing my haproxy cfg with the one that's located on master here, and haproxy restarted, but threw a warning.
```
Mar 28 19:26:51 octopi haproxy[747]: [WARNING] 086/192651 (747) : unexpected character 'i' after the timer value '15min', only (us=microseconds,ms=milliseconds,s=seconds,m=minutes,h=hours,d=days) are supported. This w…or in next versions.
Mar 28 19:26:51 octopi haproxy[747]: [WARNING] 086/192651 (747) : unexpected character 'i' after the timer value '15min', only (us=microseconds,ms=milliseconds,s=seconds,m=minutes,h=hours,d=days) are supported. This w…or in next versions.
```
This PR addresses that.
Information on the system:
``` …
```
> Fix HAProxy warning on wrong timeout abrreviation

- src/modules/octopi/filesystem/root/etc/systemd/system/webcamd.service
- src/variants/ubuntu_arm64/filesystem/root/etc/systemd/system/webcamd.service
Hello :) 
I've seen several issues related to webcamd restarting very frequently and ran in the same issue:
```
The unit webcamd.service completed and consumed the indicated resources.
Feb 08 20:34:56 octopi systemd[1]: webcamd.service: Scheduled restart job, restart counter is at 5.
```
[This mention](https://community.octoprint.org/t/webcam-freezing-after-a-few-seconds/31921/5) in the community fixed it for me and as I didn't see it in this branch yet, a PR to change this behaviour. 
Hope you are willing to merge this. 
Thanks a lot for maintaining this repository :) Keep up the good work!
> Set systemd Type to simple instead of forking

- src/modules/octopi/filesystem/root/etc/systemd/system/ffmpeg_hls.service
- src/modules/octopi/start_chroot_script
1. Building FFmpeg from source for HLS.
2. Using V4L2 M2M encoder. 
Tested on Raspberry Pi OS 32bit and 64bit. CPU load on Rpi4 is around 10%.
> HLS V4L2 M2M encoder

- src/modules/octopi/filesystem/home/root/bin/user-fix
- src/modules/octopi/filesystem/root/etc/systemd/system/user-fix.service
- src/modules/octopi/start_chroot_script
This moves the script for allowing username changes from the emergency patch in OctoPi-UpToDate, to OctoPi itself. Gina mentioned that it needed doing, so I prepared the PR.
This allows for someone to change the username in the Raspberry Pi imager before flashing the image. It does make the 'first boot' take longer as a restart is required for the changes to take affect, should they be needed.
I have tested it on a 32 bit build, although it was with FFMPEG HLS disabled due to the build time being long with that. I don't think that should impact usability of the image.
This concept has been working for a little while with the current 0.18 image patched, so hopefully this continues to work well.
> Add user-fix script to allow changing usernames

- src/variants/rpios_arm64/filesystem/root/etc/systemd/system/webcamd.service
See #788 for details. It was set in the 32 bit & 64 bit ubuntu variant, but not this one.
> Ensure webcamd service type is simple, not forking on rpios 64

- src/modules/octopi/filesystem/home/root/bin/webcamd
On the newer images (incl. 1.0.0RC2, and if you run `sudo apt upgrade` on an older one - even buster) vcgencmd has been updated with different output:
```
supported=1 detected=1, libcamera interfaces=0
```
This comparison to the exact string then broke. Users with `camera="raspi"` meant that their cameras were not detected, such as this post on the forums https://community.octoprint.org/t/cannot-get-the-picam-to-work/45922/2?u=charlie_powell. Luckily it can be used in 'usb' mode as well with the v4l2 driver.
I have not verified that this change allows webcamd to work completely with a Raspberry Pi camera as I don't have one, but the regex matching has been tested.
> Fix vcgencmd get_camera output matching with libcamera

- src/modules/octopi/filesystem/boot/octopi.txt
As wished for in #796 
I'll add this to the OctoPi-UpToDate build so it will be already done in the 1.0.0 images offered on OctoPrint's download page and on the Raspberry Pi imager, so there's IMHO no need for a RC4 for this.
> Remove raspicam references from octopi.txt

- src/modules/octopi/filesystem/root/etc/systemd/system/octoprint.service
Octoprint, because it does not specify a CA bundle anywhere, falls back to the default Python CA bundle.  This prevents a user from adding a trusted CA, and being able to use that for connections from Octoprint.
This change lets Octoprint fall back to use the Debian/Raspbian default CA bundle - so that users can update the CA certificates for the OS (and not have to find other options to figure out how to separately change Python's CA cert bundle.
> Update Octoprint Systemd Service to fall back to System CA bundle

- src/modules/octopi/filesystem/root/usr/local/bin/networkcheck
Networkcheck service is continually failing for an "unexpected end of file" error, adding in a missing if closing to resolve error
> Adding missing if closing statement

- src/modules/octopi/start_chroot_script
similar to the previous addition of system level dependencies for numpy discussed in https://github.com/guysoft/OctoPi/issues/676, those dependencies have changed with numpy version 2+. As seen on piwheels: https://www.piwheels.org/project/numpy/
> switch to modern OS dependencies for latest numpy versions
