- src/chroot_script
Log for mjpegstreamer - issue #96
> Store log for webcam daemon.

- src/filesystem/home/.octoprint/config.yaml
... because that one was buggy and I didn't notice until now, sorry.
Data structure was slightly wrong, this should however now be correct.
Sorry for that.
> Fix for my own PR #106

- src/chroot_script
- src/filesystem/home/root/bin/webcamd
- src/filesystem/root/etc/default/webcamd
- src/filesystem/root/etc/init.d/webcamd
- src/filesystem/root/etc/logrotate.d/webcamd
Can now be started/stopped/restarted via regular
sudo service webcamd (start|stop|restart)
Should make it easier to experiment with configuration
and even allow some configuration plugin for OctoPrint
at a later date if need be.
> Turned webcamDaemon into new service webcamd

- src/common.sh
> A bind mount of /dev/pts is sufficient

- .gitignore
- src/nightly_build_scripts/generate_nightly_page.js
- src/nightly_build_scripts/template.html
Nightlies are now also  limited to max. 14 entries.
Example output:
> Nicer layour for the nightly page

- src/chroot_script
- src/config
That allows using something like a caching proxy such as devpi,
speeding up the build.
> Allows defining an alternative pypi index to use during build

- src/chroot_script
This patch fixes the problem that a normal user can't ping without sudo
> Fix ping for user pi

- src/chroot_script
This is my attempt to fix #145, it uses a script from the wpa_supplicant package.
> Auto reconnect WLAN after a lost connection

- src/common.sh
While playing around with jessie lite images I noticed that the minimize function ends with an abort of resize2fs without releasing the loop device.
I noticed that the partition (enlaged with 250MB as suggested by @foosel) was not large enough for the shrinking (minimize + 200MB) at the end.
I decided to fix it by introducing a function called shrink_ext and changing the function of minimize_ext to evalute if the partition need to be enlarged or shrinked.
> Fix minimize_ext bug for 'img size < desired size'

- README.rst
(was just reading, and noticed it)
> README: s/verious/various

- README.rst
included git to list of requirement and to apt-get install list
> added git to the list of requirements

- src/chroot_script
As in the title, just fixed the pybonjour download link.
> fixed pybonjour download link

- src/filesystem/boot/octopi-network.txt
Related to https://github.com/guysoft/OctoPi/issues/222
> Adding note for MacOS users using Textedit

- src/filesystem/boot/octopi-network.txt
Made the mac banner more prominent, explained the wired config bit better and fixed a documentation bug
> Clarified some things in octopi-network.txt

- src/filesystem/root/etc/haproxy/haproxy.cfg
> Prevent duplicated X-Scheme headers in haproxy

- src/filesystem/home/pi/scripts/install-desktop
Based on current instructions found here:
https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=166806&p=1074099
> Updated install-desktop script

- src/modules/octopi/filesystem/home/pi/scripts/welcome
fix for issue #385 
rewrite of welcome script
> fix issue #385

- README.rst
CustomPiOS now depends on that. Didn't have it yet. Ran into error.
> README: Add p7zip-full to list of dependencies

- src/modules/octopi/filesystem/boot/octopi.txt
> Warning about text editors in octopi.txt

- README.rst
No need to run it manually. Has been this case for a while now actually.
Thanks for the heads-up @John-Mc
> Expansion of file system happens automatically

- src/modules/octopi/start_chroot_script
> Pin pip to 9.0.3 until OctoPrint 1.3.9 is released

- src/modules/octopi/filesystem/boot/octopi.txt
> Update links to mjpg streamer config doc

- LICENSE
- src/modules/octopi/config
Hey Community!
Would it be possible to get a detailed Temperature graph with Detailed Timestamps and a saved all values txt file or somethink similar to make my own PID tuning, bcs my printer wont have automatic PID tuning.
The request time would be nice around 0.1 seconds.
Thanks in Advanced!
> detailed temperature records

- src/modules/octopi/config
- src/modules/octopi/start_chroot_script
Switches OctoPrint's venv to Python 3
Closes #604
> Switch to Python 3

- .github/workflows/build.yml
- src/modules/octopi/config
- src/modules/octopi/start_chroot_script
Will build an image on push and daily at 00:00Z.
Resulting image gets timestamped and attached to the build as build artifact.
Not entirely happy with the download performance from the artifact servers though...
> Build image via Github Actions

- src/modules/octopi/filesystem/home/root/bin/webcamd
As reported in #641.
Closes #641
> Add 046d:0994 to broken fps devices

- src/modules/octopi/filesystem/home/root/bin/webcamd
As reported on the issue tracker.
Closes #622
Closes #638
> Add two brokenfps devices 046d:0804 & 0ac8:3450

- .gitignore
> Add vscode & idea folders to gitignore

- README.rst
See https://github.com/guysoft/OctoPi/issues/692#issuecomment-751482637 and https://github.com/guysoft/OctoPi/commit/62eabbf492c42a9e73cd4b094cbb10b7a7e19d64
> Remove preinstalled cura reference

- src/modules/octopi/filesystem/boot/octopi-network.txt
- src/variants/ubuntu_arm64/filesystem/root/etc/haproxy/haproxy.cfg
- src/variants/ubuntu_arm64/filesystem/root/etc/systemd/system/webcamd.service
- src/variants/ubuntu_arm64/post_chroot_script
All thanks for this goes to the guys in: https://github.com/guysoft/OctoPi/issues/711
Small changes in HAProxy and Webcamd-configuration
> Small fixes on the ubuntu-variant as mentioned in discussion

- src/variants/ubuntu_arm64/filesystem/root/etc/udev/rules.d/50-spi.rules
- src/variants/ubuntu_arm64/post_chroot_script
> Revert "Compatibility for ws281x on Ubuntu 64"

- src/modules/octopi/filesystem/boot/octopi.txt
> Fix typo in octopi.txt

- src/modules/octopi/filesystem/root/usr/local/bin/networkcheck
> Fix network monitoring script
